---
abstract: 'Offline implementation of USPS Postal Addressing Standards'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Address-Mail-Standardizer-USPS
no_index:
  directory:
    - inc
    - t
requires:
  Geo::Address::Mail::Standardizer: 0
  Moose: 0.90
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
